export const Stock = [
	{
		title: "Студентська знижка",
		description: "Для студентів на будь-який квест у будні дні.",
		footnote: "Пн-Чт весь день",
		stock: "-20%",
		imageSrc: "/images/stock/maniac.png",
		imageAlt: "maniac",
	},
	{
		title: "Ранкові ігри",
		description: "Знижка на ранкові сеанси до 12:00",
		footnote: "Щодня до 12:00",
		stock: "-15%",
		imageSrc: "/images/stock/clock.png",
		imageAlt: "",
	},
	{
		title: "День народження",
		description: "Імениннику знижка на гру в компанії друзів!",
		footnote: "За 3 дні до та 3 дні після ДН",
		stock: "-10%",
		imageSrc: "/images/stock/people.png",
		imageAlt: "",
	},
	{
		title: "Приведи друзів",
		description: "Прийдіть утрьох - граєте втрьох, а платите за двох.",
		footnote: "Будні дні",
		stock: "3=2",
		imageSrc: "/images/stock/house.png",
		imageAlt: "",
	},
	{
		title: "Таємна середа",
		description: "Щосереди на певні квести діє таємна знижка.",
		footnote: "Лише по середах",
		stock: "-25%",
		imageSrc: "/images/stock/forest.png",
		imageAlt: "",
	},
	{
		title: "Вечірній сеанс",
		description: "Знижка на вечірні ігри після 18:30.",
		footnote: "Будні дні після 18:30",
		stock: "-30%",
		imageSrc: "/images/stock/horror.png",
		imageAlt: "",
	},
];
